import React,{useEffect,useMemo,useState}from"react";
import{CalendarDays,Check,CheckCircle2,Clock3,LayoutDashboard,LogOut,Menu,Plus,Settings,Star,Trash2,Users,X,ArrowRight,LockKeyhole,Mail,UserRound,CalendarClock,Bell,BriefcaseBusiness,GraduationCap,House,ChevronRight,MessageCircle,Send,PanelRightClose,PanelRightOpen}from"lucide-react";
const API="http://127.0.0.1:8000",DAYS=["Mon","Tue","Wed","Thu","Fri","Sat","Sun"];
const load=(k,d)=>{try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}},save=(k,v)=>localStorage.setItem(k,JSON.stringify(v)),uid=()=>Date.now()+Math.floor(Math.random()*999);
const to24=t=>{const[m,p]=t.split(" ");let[h,n]=m.split(":").map(Number);if(p==="PM"&&h!==12)h+=12;if(p==="AM"&&h===12)h=0;return String(h).padStart(2,"0")+":"+String(n).padStart(2,"0")};
function Modal({title,onClose,children}){return <div className="overlay"><div className="modal"><div className="modalHead"><h2>{title}</h2><button className="iconBtn" onClick={onClose}><X size={18}/></button></div>{children}</div></div>}
function Login({onEnter}){const[mode,setMode]=useState("login");return <div className="authPage"><section className="authBrand"><div className="wordmark"><span>DF</span>DayFlow</div><div className="authPitch"><p className="eyebrow">YOUR TIME, ORGANIZED</p><h1>Make room for what matters.</h1><p>One place for classes, work, tasks, and meetings. DayFlow finds the time without rearranging the parts of your day that cannot move.</p><div className="authFeature"><CalendarClock/><div><b>Plan around real commitments</b><small>Classes, shifts and meetings stay fixed.</small></div></div><div className="authFeature"><CheckCircle2/><div><b>Know what to do next</b><small>Turn a busy week into a realistic plan.</small></div></div></div><small className="authFoot">DayFlow · GirlHacks 2026</small></section><section className="authPanel"><div className="authBox"><div className="mobileMark"><span>DF</span>DayFlow</div><p className="eyebrow">{mode==="login"?"WELCOME BACK":"GET STARTED"}</p><h2>{mode==="login"?"Sign in to DayFlow":"Create your account"}</h2><p className="muted">{mode==="login"?"Your week is waiting.":"Set up your schedule in a few seconds."}</p><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);onEnter(f.get("name")||f.get("email").split("@")[0])}}>{mode==="signup"&&<Field n="name" l="Name" placeholder="Your name" icon={<UserRound/>}/>}<Field n="email" l="Email" type="email" placeholder="you@example.com" required icon={<Mail/>}/><Field n="password" l="Password" type="password" placeholder="••••••••" required icon={<LockKeyhole/>}/><button className="primary authSubmit" type="submit">{mode==="login"?"Sign in":"Create account"}<ArrowRight size={17}/></button></form><div className="authSwitch">{mode==="login"?"New to DayFlow?":"Already have an account?"}<button onClick={()=>setMode(mode==="login"?"signup":"login")}>{mode==="login"?"Create account":"Sign in"}</button></div><p className="demoNote">Hackathon demo authentication · TigerData persistence connects next.</p></div></section></div>}
export default function App(){
 const[session,setSession]=useState(()=>load("dayflow_session",null)),[tasks,setTasks]=useState(()=>load("dayflow_tasks",[])),[blocks,setBlocks]=useState(()=>load("dayflow_blocks",[])),[plan,setPlan]=useState(()=>load("dayflow_plan",[])),[profile,setProfile]=useState(()=>load("dayflow_profile",{name:"You",start:"08:00",end:"21:00"})),[meetings,setMeetings]=useState(()=>load("dayflow_meetings",[])),[status,setStatus]=useState("Connecting"),[modal,setModal]=useState(null),[options,setOptions]=useState([]),[nav,setNav]=useState("Overview"),[chatOpen,setChatOpen]=useState(true),[chatInput,setChatInput]=useState(""),[chat,setChat]=useState([{who:"ai",text:"Hi — tell me what you need to get done and I’ll point you to the right place."}]);
 useEffect(()=>{fetch(API+"/api/health").then(r=>r.json()).then(()=>setStatus("Online")).catch(()=>setStatus("Offline"))},[]);
 useEffect(()=>save("dayflow_tasks",tasks),[tasks]);useEffect(()=>save("dayflow_blocks",blocks),[blocks]);useEffect(()=>save("dayflow_plan",plan),[plan]);useEffect(()=>save("dayflow_profile",profile),[profile]);useEffect(()=>save("dayflow_meetings",meetings),[meetings]);useEffect(()=>save("dayflow_session",session),[session]);
 const availability=useMemo(()=>DAYS.map((_,day)=>({day,start:profile.start,end:profile.end})),[profile]),open=tasks.filter(t=>!t.completed),minutes=open.reduce((a,t)=>a+Number(t.duration),0);
 if(!session)return <Login onEnter={name=>{setSession({name});setProfile(p=>({...p,name:name||p.name}))}}/>;
 async function planWeek(){try{const r=await fetch(API+"/api/plan",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({tasks:open,fixed_blocks:blocks,availability})}),d=await r.json();if(!r.ok)throw Error();setPlan(d.schedule)}catch{alert("DayFlow could not reach FastAPI on port 8000.")}}
 function task(e){e.preventDefault();const f=new FormData(e.currentTarget);setTasks(v=>[...v,{id:uid(),title:f.get("title"),category:f.get("category"),date:f.get("date")||null,duration:+f.get("duration"),priority:f.get("priority"),completed:false,starred:false}]);setModal(null)}
 function block(e){e.preventDefault();const f=new FormData(e.currentTarget);setBlocks(v=>[...v,{id:uid(),title:f.get("title"),type:f.get("type"),day:+f.get("day"),start:f.get("start"),end:f.get("end")}]);setModal(null)}
 async function meeting(e){e.preventDefault();const f=new FormData(e.currentTarget),payload={title:f.get("title"),duration:+f.get("duration"),urgency:f.get("urgency"),participants:[{name:f.get("person"),availability}],fixed_blocks:blocks,availability,preferred_after:f.get("after")||null};try{const r=await fetch(API+"/api/meetings/propose",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)}),d=await r.json();setOptions(d.options||[]);setModal({type:"options",title:payload.title})}catch{alert("Meeting service is offline.")}}
 async function sendChat(e){
  e.preventDefault();
  const message=chatInput.trim();
  if(!message)return;
  setChat(v=>[...v,{who:"user",text:message}]);
  setChatInput("");
  try{
   const r=await fetch(API+"/api/chat",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({message,tasks,fixed_blocks:blocks})});
   const d=await r.json();
   setChat(v=>[...v,{who:"ai",text:d.message}]);
   if(d.action==="task")setModal("task");
   if(d.action==="meeting")setModal("meeting");
  }catch{
   setChat(v=>[...v,{who:"ai",text:"I can’t reach the DayFlow backend right now. Check that FastAPI is running on port 8000."}]);
  }
 }
 function confirm(o,title){const b={id:uid(),title,type:"Meeting",day:o.day,start:to24(o.start),end:to24(o.end)};setBlocks(v=>[...v,b]);setMeetings(v=>[...v,{...b,date:o.date}]);setModal(null)}
 const navs=[["Overview",LayoutDashboard],["Calendar",CalendarDays],["Tasks",CheckCircle2],["Meetings",Users],["Reminders",Bell]];
 return <div className="app"><aside className="rail"><div className="wordmark"><span>DF</span>DayFlow</div><nav>{navs.map(([n,I])=><button className={nav===n?"active":""} onClick={()=>setNav(n)} key={n}><I size={18}/>{n}{n==="Tasks"&&open.length>0?<em>{open.length}</em>:null}</button>)}</nav><div className="railBottom"><button onClick={()=>setModal("profile")}><Settings size={18}/>Settings</button><div className="account"><div className="avatar">{(profile.name||"Y")[0].toUpperCase()}</div><div><b>{profile.name}</b><small>{status} · FastAPI</small></div><button className="logout" onClick={()=>setSession(null)}><LogOut size={16}/></button></div></div></aside>
 <main className="workspace"><header><div><p className="eyebrow">{nav.toUpperCase()}</p><h1>{nav==="Overview"?"Your week at a glance":nav}</h1><p className="muted">{nav==="Overview"?"Keep the fixed stuff fixed. We’ll fit the rest around it.":"Everything stays connected to your DayFlow schedule."}</p></div><div className="topActions"><button className="secondary" onClick={()=>setModal("task")}><Plus size={16}/>Task</button><button className="primary" onClick={planWeek}><CalendarClock size={16}/>Plan week</button></div></header>
 {nav==="Overview"&&<><section className="stats"><Stat icon={<CheckCircle2/>} label="Open tasks" value={open.length}/><Stat icon={<Clock3/>} label="Work to place" value={(minutes/60).toFixed(1)+"h"}/><Stat icon={<CalendarDays/>} label="Fixed blocks" value={blocks.length}/><Stat icon={<Users/>} label="Meetings" value={meetings.length}/></section><Calendar blocks={blocks} plan={plan} setBlocks={setBlocks} setModal={setModal}/><section className="lower"><Tasks tasks={tasks} setTasks={setTasks} setModal={setModal}/><div className="card nextCard"><div className="sectionIcon"><CalendarClock/></div><p className="eyebrow">NEXT STEP</p><h3>Build a realistic week.</h3><p>DayFlow uses your availability and fixed commitments before placing flexible work.</p><button className="primary full" onClick={planWeek}>Plan my week<ArrowRight size={16}/></button></div></section></>}
 {nav==="Calendar"&&<Calendar blocks={blocks} plan={plan} setBlocks={setBlocks} setModal={setModal}/>}
 {nav==="Tasks"&&<Tasks tasks={tasks} setTasks={setTasks} setModal={setModal}/>}
 {nav==="Meetings"&&<section className="card pageCard"><div className="cardHead"><div><p className="eyebrow">MEETINGS</p><h3>Find time without the back-and-forth.</h3></div><button className="primary" onClick={()=>setModal("meeting")}><Plus size={16}/>New meeting</button></div>{meetings.length?meetings.map(m=><div className="meetingRow" key={m.id}><div className="sectionIcon"><Users/></div><div><b>{m.title}</b><small>{DAYS[m.day]} · {m.start}–{m.end}</small></div></div>):<Empty icon={<Users/>} title="No meetings yet" text="Create one and DayFlow will suggest three times."/>}</section>}
 {nav==="Reminders"&&<section className="card pageCard"><Empty icon={<Bell/>} title="Nothing urgent" text="Reminders will appear here as deadlines and meetings get closer."/></section>}
 </main>
 <button className="chatToggle" onClick={()=>setChatOpen(v=>!v)} aria-label="Toggle DayFlow assistant">{chatOpen?<PanelRightClose size={19}/>:<MessageCircle size={19}/>}</button>
 {chatOpen&&<aside className="assistantPanel">
   <div className="assistantHead"><div><span className="assistantMark"><MessageCircle size={16}/></span><div><b>DayFlow Assistant</b><small>Ask about your week</small></div></div><button className="iconBtn" onClick={()=>setChatOpen(false)}><X size={17}/></button></div>
   <div className="assistantQuick"><button onClick={planWeek}><CalendarClock size={14}/>Plan my week</button><button onClick={()=>setModal("task")}><Plus size={14}/>Add task</button><button onClick={()=>setModal("meeting")}><Users size={14}/>Find meeting time</button></div>
   <div className="chatMessages">{chat.map((m,i)=><div key={i} className={"chatMessage "+m.who}>{m.text}</div>)}</div>
   <form className="chatComposer" onSubmit={sendChat}><textarea value={chatInput} onChange={e=>setChatInput(e.target.value)} placeholder="What do you need help with?"/><button type="submit" aria-label="Send"><Send size={16}/></button></form>
 </aside>}
 {modal==="task"&&<Modal title="Add task" onClose={()=>setModal(null)}><form onSubmit={task}><Field n="title" l="Task" required/><div className="row"><Select n="category" l="Category" opts={["School","Work","Personal","Club"]}/><Field n="duration" l="Minutes" type="number" min="15" defaultValue="60"/></div><div className="row"><Field n="date" l="Deadline" type="date"/><Select n="priority" l="Priority" opts={["high","medium","low"]}/></div><Submit/></form></Modal>}
 {modal==="block"&&<Modal title="Add fixed commitment" onClose={()=>setModal(null)}><form onSubmit={block}><Field n="title" l="Title" required/><div className="row"><Select n="type" l="Type" opts={["Class","Work","Personal","Meeting"]}/><Select n="day" l="Day" opts={DAYS} values={[0,1,2,3,4,5,6]}/></div><div className="row"><Field n="start" l="Start" type="time" defaultValue="09:00"/><Field n="end" l="End" type="time" defaultValue="10:00"/></div><Submit/></form></Modal>}
 {modal==="profile"&&<Modal title="Schedule settings" onClose={()=>setModal(null)}><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);setProfile({name:f.get("name"),start:f.get("start"),end:f.get("end")});setModal(null)}}><Field n="name" l="Name" defaultValue={profile.name}/><div className="row"><Field n="start" l="Day starts" type="time" defaultValue={profile.start}/><Field n="end" l="Day ends" type="time" defaultValue={profile.end}/></div><Submit/></form></Modal>}
 {modal==="meeting"&&<Modal title="Find a meeting time" onClose={()=>setModal(null)}><form onSubmit={meeting}><Field n="title" l="Meeting" required/><Field n="person" l="With" placeholder="Name"/><div className="row"><Field n="duration" l="Minutes" type="number" defaultValue="60"/><Select n="urgency" l="Priority" opts={["normal","urgent"]}/></div><Field n="after" l="Prefer after" type="time"/><Submit text="Find 3 times"/></form></Modal>}
 {modal?.type==="options"&&<Modal title="Choose a time" onClose={()=>setModal(null)}><div className="options">{options.length?options.map(o=><button key={o.id} onClick={()=>confirm(o,modal.title)}><CalendarClock/><div><b>{DAYS[o.day]} · {o.date}</b><span>{o.start} – {o.end}</span><small>{o.reason}</small></div><ChevronRight/></button>):<Empty icon={<Clock3/>} title="No match found" text="Try broader availability."/ >}</div></Modal>}
 </div>
}
function Calendar({blocks,plan,setBlocks,setModal}){return <section className="card calendar"><div className="cardHead"><div><p className="eyebrow">SCHEDULE</p><h3>This week</h3></div><button className="secondary" onClick={()=>setModal("block")}><Plus size={16}/>Fixed block</button></div><div className="week">{DAYS.map((d,day)=><div className="day" key={d}><div className="dayName">{d}</div><div className="dayBody">{blocks.filter(x=>x.day===day).map(x=><Block key={x.id} x={x} remove={()=>setBlocks(v=>v.filter(q=>q.id!==x.id))}/>)}{plan.filter(x=>x.day===day).map((x,i)=><Block key={"p"+i} x={{...x,start:to24(x.start),end:to24(x.end),type:"Focus"}}/>)}</div></div>)}</div></section>}
function Tasks({tasks,setTasks,setModal}){return <section className="card tasksCard"><div className="cardHead"><div><p className="eyebrow">TASKS</p><h3>What needs your attention</h3></div><button className="secondary" onClick={()=>setModal("task")}><Plus size={16}/>Add task</button></div>{tasks.length?tasks.map(t=><div className={"task "+(t.completed?"done":"")} key={t.id}><button className="check" onClick={()=>setTasks(v=>v.map(x=>x.id===t.id?{...x,completed:!x.completed}:x))}>{t.completed&&<Check size={13}/>}</button><div className="taskText"><b>{t.title}</b><small>{t.category} · {t.duration} min {t.date?"· "+t.date:""}</small></div><button className={"iconBtn star "+(t.starred?"on":"")} onClick={()=>setTasks(v=>v.map(x=>x.id===t.id?{...x,starred:!x.starred}:x))}><Star size={16}/></button><span className={"priority "+t.priority}>{t.priority}</span><button className="iconBtn" onClick={()=>setTasks(v=>v.filter(x=>x.id!==t.id))}><Trash2 size={16}/></button></div>):<Empty icon={<CheckCircle2/>} title="Your list is clear" text="Add a task when something comes up."/>}</section>}
function Block({x,remove}){const icons={Class:GraduationCap,Work:BriefcaseBusiness,Personal:House,Meeting:Users,Focus:Clock3},I=icons[x.type]||CalendarDays;return <div className={"block "+x.type.toLowerCase()}><I size={12}/><div><b>{x.title}</b><small>{x.start}–{x.end}</small></div>{remove&&<button onClick={remove}>×</button>}</div>}
function Stat({icon,label,value}){return <div className="stat"><span>{icon}</span><div><small>{label}</small><b>{value}</b></div></div>}
function Empty({icon,title,text}){return <div className="empty"><span>{icon}</span><b>{title}</b><p>{text}</p></div>}
function Field({n,l,icon,...p}){return <label>{l}<div className={icon?"inputIcon":""}>{icon}<input name={n} {...p}/></div></label>}
function Select({n,l,opts,values}){return <label>{l}<select name={n}>{opts.map((o,i)=><option key={o} value={values?values[i]:o}>{o}</option>)}</select></label>}
function Submit({text="Save"}){return <button className="primary submit" type="submit">{text}</button>}
