import React,{useEffect,useState}from"react";import{createRoot}from"react-dom/client";import{CalendarDays,Plus,BookOpen,Briefcase,Clock3,LogOut,X,Users,RefreshCw}from"lucide-react";import{clearToken,createEvent,createTask,events,getToken,login,me,removeEvent,removeTask,signup,tasks,setTaskStatus,findSharedSlots,createSharedMeeting,confirmSharedMeeting,calendarConnections,googleCalendarConnect,syncGoogleCalendar}from"./api";import"./styles.css";

function Auth({onReady}){
 const[signupMode,setSignupMode]=useState(false),[error,setError]=useState(""),[busy,setBusy]=useState(false);
 const[form,setForm]=useState({name:"",email:"",password:"",mode:"student"});
 const submit=async e=>{e.preventDefault();setBusy(true);setError("");try{const data=signupMode?await signup(form):await login({email:form.email,password:form.password});onReady(data.user)}catch(err){setError(err.message)}finally{setBusy(false)}};
 return <main className="auth"><section className="authHero"><div className="brand"><span>DF</span><b>DayFlow</b></div><div><small>YOUR PERSONAL AI SECRETARY</small><h1>Make room for what matters.</h1><p>Classes, work, tasks, and your real schedule in one place.</p></div><b>GirlHacks 2026</b></section><section className="authForm"><form onSubmit={submit}><small>{signupMode?"GET STARTED":"WELCOME BACK"}</small><h2>{signupMode?"Create your DayFlow":"Sign in to DayFlow"}</h2>{signupMode&&<><label>Name<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} required/></label><label>I am a<select value={form.mode} onChange={e=>setForm({...form,mode:e.target.value})}><option value="student">Student</option><option value="office">Office worker</option><option value="other">Other</option></select></label></>}<label>Email<input type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} required/></label><label>Password<input type="password" minLength="8" value={form.password} onChange={e=>setForm({...form,password:e.target.value})} required/></label>{error&&<p className="error">{error}</p>}<button className="send" disabled={busy}>{busy?"Working...":signupMode?"Create account":"Sign in"}</button><p>{signupMode?"Already have an account? ":"New to DayFlow? "}<button type="button" className="link" onClick={()=>{setSignupMode(!signupMode);setError("")}}>{signupMode?"Sign in":"Create account"}</button></p></form></section></main>
}

function Planner({user,onLogout}){
 const[eventList,setEvents]=useState([]),[taskList,setTasks]=useState([]),[modal,setModal]=useState(null),[taskModal,setTaskModal]=useState(false),[meetModal,setMeetModal]=useState(false),[slotResult,setSlotResult]=useState(null),[connections,setConnections]=useState([]),[error,setError]=useState("");
 const load=async()=>{try{const[e,t,c]=await Promise.all([events(),tasks(),calendarConnections()]);setEvents(e);setTasks(t);setConnections(c)}catch(err){setError(err.message)}};
 useEffect(()=>{load()},[]);
 const saveEvent=async e=>{e.preventDefault();try{await createEvent({title:modal.title,start:modal.start,end:modal.end,event_type:modal.type,flexibility:"fixed"});setModal(null);await load()}catch(err){setError(err.message)}};
 const saveTask=async e=>{e.preventDefault();const fd=new FormData(e.currentTarget);try{await createTask({title:fd.get("title"),category:fd.get("category"),estimated_minutes:Number(fd.get("minutes")),priority:fd.get("priority"),flexibility:"flexible"});setTaskModal(false);await load()}catch(err){setError(err.message)}};
 const connectGoogle=async()=>{try{const x=await googleCalendarConnect();window.location.href=x.authorization_url}catch(err){setError(err.message)}};
 const syncGoogle=async()=>{try{await syncGoogleCalendar();await load()}catch(err){setError(err.message)}};
 const findTime=async e=>{e.preventDefault();const f=new FormData(e.currentTarget);const body={title:f.get("title"),emails:f.get("emails").split(",").map(x=>x.trim()).filter(Boolean),duration_minutes:Number(f.get("duration")),window_start:f.get("start"),window_end:f.get("end")};try{const created=await createSharedMeeting(body);setSlotResult(created)}catch(err){setError(err.message)}};
 const chooseSlot=async start=>{try{await confirmSharedMeeting(slotResult.meeting.id,start);setSlotResult(null);setMeetModal(false);await load()}catch(err){setError(err.message)}};
 const logout=()=>{clearToken();onLogout()};
 return <main><aside className="rail"><div className="brand"><span>DF</span><b>DayFlow</b></div><div><h1>A little structure.<br/>A lot more breathing room.</h1><p>Welcome, {user.name}. Your DayFlow is backed by TigerData.</p></div><div className="quick"><small>QUICK ACTIONS</small><button onClick={()=>setModal({type:"Class",title:"",start:"",end:""})}><BookOpen/>Add a class<Plus/></button><button onClick={()=>setModal({type:"Work",title:"",start:"",end:""})}><Briefcase/>Add a work shift<Plus/></button><button onClick={()=>setTaskModal(true)}><Clock3/>Add a task<Plus/></button></div><button className="shareBtn" onClick={()=>setMeetModal(true)}><Users/> Find a shared time</button><button className="logout" onClick={logout}><LogOut/> Sign out</button></aside><section className="content"><div className="top"><div><small>MY DAYFLOW</small><h2>Welcome, {user.name} · Your real week</h2></div><div>{connections.some(c=>c.provider==="google")?<button className="ghost" onClick={syncGoogle}><RefreshCw/>Sync Google</button>:<button className="ghost" onClick={connectGoogle}>Connect Google Calendar</button>}<button className="add" onClick={()=>setModal({type:"Personal",title:"",start:"",end:""})}><Plus/>Add event</button></div></div>{error&&<p className="error banner">{error}</p>}<section className="calendar"><header><div><CalendarDays/><b>Saved events</b></div><span>{eventList.length} in TigerData</span></header><div className="realList">{eventList.length?eventList.map(x=><article key={x.id}><div><small>{x.event_type}</small><b>{x.title}</b><span>{new Date(x.starts_at).toLocaleString()} → {new Date(x.ends_at).toLocaleString()}</span></div><button onClick={async()=>{await removeEvent(x.id);load()}}>Delete</button></article>):<div className="empty">No events yet. Add your first real calendar event.</div>}</div></section><div className="bottom"><section className="card"><div><h3>Tasks</h3><button onClick={()=>setTaskModal(true)}>+ Add task</button></div>{taskList.length?taskList.map(t=><article className={"task priority-"+t.priority} key={t.id}><input type="checkbox" checked={t.completed} onChange={async e=>{await setTaskStatus(t.id,e.target.checked);load()}}/><div><b>{t.priority==="high"?"★ ":""}{t.title}</b><small>{t.priority} priority · {t.category} · {t.estimated_minutes} min</small></div><button onClick={async()=>{await removeTask(t.id);load()}}>Delete</button></article>):<p>No tasks yet.</p>}</section><section className="change"><div><h3>Connected for real</h3><p>Events and tasks on this screen are now loaded from your authenticated TigerData account instead of temporary React state.</p></div></section></div></section>
 {modal&&<div className="overlay"><form className="modal" onSubmit={saveEvent}><button type="button" className="close" onClick={()=>setModal(null)}><X/></button><h2>Add {modal.type}</h2><label>Title<input value={modal.title} onChange={e=>setModal({...modal,title:e.target.value})} required/></label><label>Start<input type="datetime-local" value={modal.start} onChange={e=>setModal({...modal,start:e.target.value})} required/></label><label>End<input type="datetime-local" value={modal.end} onChange={e=>setModal({...modal,end:e.target.value})} required/></label><button className="send">Save to DayFlow</button></form></div>}
 {taskModal&&<div className="overlay"><form className="modal" onSubmit={saveTask}><button type="button" className="close" onClick={()=>setTaskModal(false)}><X/></button><h2>Add task</h2><label>Task<input name="title" required/></label><label>Category<select name="category"><option>School</option><option>Work</option><option>Personal</option></select></label><label>Estimated minutes<input name="minutes" type="number" min="5" defaultValue="60" required/></label><label>Priority<select name="priority" defaultValue="medium"><option value="high">High</option><option value="medium">Medium</option><option value="low">Low</option></select></label><button className="send">Save task</button></form></div>}
 {meetModal&&<div className="overlay"><form className="modal" onSubmit={findTime}><button type="button" className="close" onClick={()=>{setMeetModal(false);setSlotResult(null)}}><X/></button><small>NO TEXTING BACK AND FORTH</small><h2>Find everyone's free slot</h2><label>Meeting name<input name="title" required/></label><label>DayFlow users' emails<input name="emails" placeholder="friend@example.com, teammate@example.com" required/></label><label>Duration (minutes)<input name="duration" type="number" min="15" step="15" defaultValue="60" required/></label><label>Search from<input name="start" type="datetime-local" required/></label><label>Search until<input name="end" type="datetime-local" required/></label><button className="send">Find shared availability</button>{slotResult&&<div className="slotList"><b>Best free slots</b>{slotResult.slots.length?slotResult.slots.map(s=><button type="button" key={s.start} onClick={()=>chooseSlot(s.start)}>{new Date(s.start).toLocaleString()} · everyone free</button>):<p>No common slot in this window.</p>}</div>}</form></div>}</main>
}

function App(){const[user,setUser]=useState(null),[loading,setLoading]=useState(Boolean(getToken()));useEffect(()=>{if(!getToken())return;me().then(setUser).catch(()=>clearToken()).finally(()=>setLoading(false))},[]);if(loading)return <div className="loading">Opening DayFlow…</div>;return user?<Planner user={user} onLogout={()=>setUser(null)}/>:<Auth onReady={setUser}/>};createRoot(document.getElementById("root")).render(<App/>);
